[build]
  publish = "public"
  command = "cd themes/deep-blue-theme && npm run build && hugo --gc --minify --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.96.0"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "repo"
HUGO_BASEURL = "/"
