[build]
  publish = "public"
  command = "NODE_ENV=production hugo --gc --minify --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.96.0"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "repo"
HUGO_BASEURL = "/"
