baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'deep-blue-theme'
themesDir = '../..'
disableHugoGeneratorInject = true

# Main Menu
[[menu.main]]
name = "About"
url = "#about"
weight = 1
[[menu.main]]
name = "Services"
url = "#services"
weight = 2
[[menu.main]]
name = "Writings"
url = "#writings"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
dateFormat = "02 Jan 2006"
